### DISCUSSION TITLE
[v6] useMatch params is always empty

### DISCUSSION THREAD

**Discussion by shahafa** [remix-run/react-router#8298] [Q&A]
I'm trying to migrate v5 to v6,

I have the following routes and Page component
```
          <Routes>
            <Route path="/page">
              <Route path=":id" element={<Page />} />
              <Route index element={<Page />} />
            </Route>
          </Routes>
```

```
const Page = () => {
  const location = useLocation();
  const match = useMatch(location.pathname);
  console.log(match);
  ...
```

I navigate to /page/123 and print `match` inside the `Page` component
the match `params` attribute is an empty object and not including the `id`
```
params: {}
pathname: "/page/123"
pathnameBase: "/page/123"
pattern:
  caseSensitive: false
  end: true
  path: "/page/123"
```

Am I missing something or this is a bug?

I also tried
```
          <Routes>
              <Route path="/page/:id" element={<Page />} />
              <Route path="/page" element={<Page />} />
          </Routes>
```
Same problem
