### DISCUSSION TITLE
Navigate state with circular reference makes a new page reloading instead of SPA routing

### DISCUSSION THREAD

**Discussion by dRoysch** [remix-run/react-router#8932] [Q&A]
Hello, 

when I use the above code this make a reloading of a new page

```
const elements = {foo: 'bar', html_foo: <span>bar</span>}

    navigate(`form/`, {
      state: elements ,
    });
```

And of course when using `const location = useLocation()` in form route component and consoling the state this is null.

```
location:
    hash: ""
    key: "default"
    pathname: "/form"
    search: ""
    state: null
    [[Prototype]]: Object
```

This behavior has a reason of been?

Thanks!
