### ISSUE TITLE
[Bug]: Content briefly appears during route transitions using react-router-dom

### ISSUE THREAD

**Issue by rossgalloway** [remix-run/react-router#10532]
### What version of React Router are you using?

6.11.2

### Steps to Reproduce

A simplified, reproducible example of the issue is provided below. This example includes a basic setup with three routes (Home, PageOne, and PageTwo). There is a useState and useEffect hook setup to handle the transition effect between route changes. The transition is a simple fade-in/out effect controlled by CSS and JavaScript.

Example code:
``` ts
// src/App.tsx

import React, { useState, useEffect } from 'react'
import {
  Routes,
  Route,
  useLocation,
  Link,
} from 'react-router-dom'
import './App.css'

const Home = () => <h1>Home</h1>
const PageOne = () => <h1>Page One</h1>
const PageTwo = () => <h1>Page Two</h1>

const App: React.FC = () => {
  const [showContent, setShowContent] = useState(true)

  const location = useLocation()

  useEffect(() => {
    setShowContent(false)

    const timer = setTimeout(() => {
      setShowContent(true)
    }, 500)

    return () => clearTimeout(timer)
  }, [location])

  return (
    <div>
      <Link className="button" to="/one">Page One</Link>
      <Link className="button" to="/two">Page Two</Link>
      <Link className="button" to="/">Home</Link>

      <div className={`content ${showContent ? 'active' : ''}`}>
        <Routes>
          <Route index element={<Home />} />
          <Route path="one" element={<PageOne />} />
          <Route path="two" element={<PageTwo />} />
        </Routes>
      </div>
    </div>
  )
}

export default App
```
``` css
.content {
  width: 100vw;
  height: 100vh;
  opacity: 0;
}

.content.active {
  opacity: 1;
  transition: opacity 0.5s ease-in-out;
}

.button {
  display: inline-block;
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #1a1a1a;
  cursor: pointer;
  transition: border-color 0.25s;
  color: #646cff;
  text-decoration: none;
  text-align: center;
}

.button:hover {
  border-color: #646cff;
}

.button:focus,
.button:focus-visible {
  outline: 4px auto -webkit-focus-ring-color;
}

@media (prefers-color-scheme: light) {
  :root {
    color: #213547;
    background-color: #ffffff;
  }
  a:hover {
    color: #747bff;
  }
  .button {
    background-color: #f9f9f9;
  }
}
```

You can also find a repository of the example with working and not working branches here: https://github.com/rossgalloway/react-router-issue. I fixed the issue for my site by explicitly turning off the content in the page to be navigated to upon clicking on the link. 

### Expected Behavior

A clean transition from one page to another without any initial rendering of the final content.

### Actual Behavior

When using the react-router-dom library in combination with CSS transitions to manage route changes and transitions, a momentary flash of the destination page content occurs before the transition effect begins. The brief appearance of content doesn't happen consistently – it appears about half the time. The issue seems to be particularly tied to using react-router-dom's Link component for navigation.
